/// The journey explorer shares one selected time interval across every signal.
/// Runtime text is rendered with textContent; no collected HTML is evaluated.
const journeyHtml = r'''
<section class="panel journey-panel" id="journey-panel" aria-labelledby="journey-title" hidden>
<div class="row"><div><div class="eyebrow">The journey your test took</div><h2 id="journey-title">Tests, screens, and operations</h2><p class="subtle">Select a moment to inspect its rendering, memory, sampled code, and widget evidence together.</p></div><button id="journey-all" type="button">Entire captured journey</button></div>
<div class="journey-layout"><nav aria-label="Captured journey" id="journey-items"></nav><div class="journey-content">
<div class="row"><div><h3 id="journey-selection-title" tabindex="-1">Entire captured journey</h3><p id="journey-selection-note" class="subtle"></p></div><span id="journey-duration" class="pill"></span></div>
<svg id="journey-chart" viewBox="0 0 760 255" role="img" aria-label="Shared timeline of journey and telemetry"></svg>
<div class="controls"><label for="journey-start">From <output id="journey-start-label"></output><input id="journey-start" type="range" min="0" max="1" step="1"></label><label for="journey-end">To <output id="journey-end-label"></output><input id="journey-end" type="range" min="0" max="1" step="1"></label></div>
<p id="journey-window" class="subtle" aria-live="polite"></p>
<p id="journey-finding" class="journey-finding" aria-live="polite"></p>
<div class="journey-stats" id="journey-stats"></div>
<div class="journey-tabs" role="tablist" aria-label="Selected interval evidence"><button type="button" role="tab" id="journey-tab-frames" aria-controls="journey-evidence-frames" aria-selected="true">Frames</button><button type="button" role="tab" id="journey-tab-memory" aria-controls="journey-evidence-memory" aria-selected="false" tabindex="-1">Memory</button><button type="button" role="tab" id="journey-tab-cpu" aria-controls="journey-evidence-cpu" aria-selected="false" tabindex="-1">Sampled code</button><button type="button" role="tab" id="journey-tab-widgets" aria-controls="journey-evidence-widgets" aria-selected="false" tabindex="-1">Widgets & sources</button></div>
<section role="tabpanel" tabindex="0" id="journey-evidence-frames" aria-labelledby="journey-tab-frames"><p class="subtle">Calibrated boundaries support attribution. Approximate or unfinished windows show nearby evidence, not exact attribution. Boundary overlaps are counted separately. Build and raster durations are never added.</p><div id="journey-frames-content"></div></section>
<section role="tabpanel" tabindex="0" id="journey-evidence-memory" aria-labelledby="journey-tab-memory" hidden><p class="subtle">Snapshots cover the process. Each isolate-group heap is counted once. RSS already includes memory beyond Dart; do not add it to Dart heap. A rise over one interval does not establish a leak.</p><div id="journey-memory-content"></div></section>
<section role="tabpanel" tabindex="0" id="journey-evidence-cpu" aria-labelledby="journey-tab-cpu" hidden><p class="subtle">Self samples count the executing leaf function; inclusive share counts appearances anywhere on the stack. It is not CPU utilization or exact function duration. Parent and child shares overlap.</p><label><input id="journey-app-code" type="checkbox"> Application code only</label><div id="journey-cpu-content"></div></section>
<section role="tabpanel" tabindex="0" id="journey-evidence-widgets" aria-labelledby="journey-tab-widgets" hidden><p class="subtle">Runtime locations, declared context, and local source candidates have different evidence strengths. Rebuild counts are not widget duration. Temporal overlap does not prove a cause.</p><div id="journey-widgets-content"></div></section>
<details><summary>Clock, attribution, and missing signals</summary><ul id="journey-limits" class="limits"></ul><pre id="journey-capabilities"></pre></details>
</div></div></section>
''';
const journeyStyle = r'''
.journey-panel{margin-bottom:28px}.journey-finding{background:var(--soft);border-left:3px solid var(--accent);padding:16px;border-radius:6px;font-size:14px;line-height:1.7}.journey-source button{font-size:10px;padding:3px 7px;margin:4px 0}.journey-layout{display:grid;grid-template-columns:235px minmax(0,1fr);gap:22px;margin-top:22px}.journey-content{min-width:0}#journey-items{max-height:660px;overflow:auto;border-right:1px solid var(--line);padding-right:12px;display:flex;flex-direction:column;gap:7px}.journey-item{text-align:left;border-color:transparent;font-weight:500;line-height:1.4;padding:10px 12px}.journey-item small{display:block;font-size:11px;margin-top:4px}.journey-item[aria-current=true]{background:var(--soft);border-color:var(--accent)}.journey-item .journey-kind{text-transform:uppercase;font-size:10px;letter-spacing:.07em;color:var(--accent);font-weight:700;display:block;margin-bottom:5px}.journey-item.depth-1{margin-left:10px}.journey-item.depth-2{margin-left:20px}.journey-item.depth-3{margin-left:30px}#journey-chart{width:100%;height:auto;margin-top:20px;min-height:170px}.journey-stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin:16px 0}.journey-stat{border:1px solid var(--line);border-radius:9px;padding:12px;font-size:12px;line-height:1.45}.journey-stat strong{display:block;font-size:20px;letter-spacing:-.025em;margin-bottom:4px}.journey-tabs{display:flex;gap:5px;flex-wrap:wrap;margin:24px 0 16px;border-bottom:1px solid var(--line);padding-bottom:10px}.journey-tabs button{font-size:12px;padding:7px 10px}.journey-tabs button[aria-selected=true]{background:var(--soft);border-color:var(--accent)}.journey-source{font:11px/1.6 ui-monospace,monospace;white-space:normal;overflow-wrap:anywhere;min-width:170px}.journey-source span{display:block;color:var(--muted)}.journey-evidence-note{margin:12px 0;font-size:13px;color:var(--muted)}.journey-panel td{white-space:normal}.journey-panel table{min-width:460px}.journey-panel td:first-child{max-width:250px;overflow-wrap:anywhere}@media(max-width:820px){.journey-layout{grid-template-columns:1fr}#journey-items{max-height:210px;border-right:none;border-bottom:1px solid var(--line);padding:0 0 12px}.journey-stats{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}
''';
const journeyScript = r'''
const jData=report.journey;
if(jData){
 $('journey-panel').hidden=false;if($('journey-link'))$('journey-link').hidden=false;
 const jItems=jData.items||[],jFrames=jData.frames||[],jMemory=jData.memory||[],jCpu=jData.cpu||[],jTraces=jData.traces||[],jRebuilds=jData.widgetRebuilds||[],jGc=jData.gc||[];
 const jPoints=[...jFrames.flatMap(x=>[x.startMicros,x.endMicros]),...jItems.flatMap(x=>[x.startMicros,x.endMicros??x.observedEndMicros]),...jMemory.map(x=>x.micros),...jCpu.flatMap(x=>[x.startMicros,x.endMicros])].filter(finite);
 let jMin=Infinity,jMax=-Infinity;for(const p of jPoints){jMin=Math.min(jMin,p);jMax=Math.max(jMax,p);}if(!finite(jMin))jMin=0;if(!finite(jMax)||jMax<=jMin)jMax=jMin+1;let jMargin=0;for(const e of [...jFrames,...jMemory,...jItems])if(finite(e.uncertaintyMicros))jMargin=Math.max(jMargin,e.uncertaintyMicros);jMin=Math.max(0,jMin-jMargin);jMax+=jMargin;
 let jInterval={startMicros:jMin,endMicros:jMax,uncertaintyMicros:0},jActive=null;
 const jById=new Map(jItems.map(i=>[i.id,i]));
 const jAppUris=new Set((report.sourceIndex?.entries||[]).flatMap(e=>[e.uri,e.path]));$('journey-app-code').checked=jAppUris.size>0;$('journey-app-code').disabled=!jAppUris.size;
 const jIsApp=fn=>jAppUris.has(fn.uri)||(fn.sourceCandidates||[]).length>0;
 const jBytes=v=>finite(v)?fmt(v/1048576,2)+' MiB':'Unavailable';
 const jPhase=f=>Math.max(f.buildMicros||0,f.rasterMicros||0);
 function jInside(e){const a=e.startMicros??e.micros,b=e.endMicros??e.micros,u=e.uncertaintyMicros;if(!finite(u))return false;const iu=finite(jInterval.uncertaintyMicros)?jInterval.uncertaintyMicros:0;if(jInterval.connection!=null&&e.connection!=null&&String(jInterval.connection)!==String(e.connection))return false;return finite(a)&&finite(b)&&a-u>=jInterval.startMicros+iu&&b+u<=jInterval.endMicros-iu;}
 function jOverlap(e){const a=e.startMicros??e.micros,b=e.endMicros??e.micros,u=finite(e.uncertaintyMicros)?e.uncertaintyMicros:0;if(jInterval.connection!=null&&e.connection!=null&&String(jInterval.connection)!==String(e.connection))return false;return finite(a)&&finite(b)&&a-u<=jInterval.endMicros&&b+u>=jInterval.startMicros;}
 function jTable(parent,headers,rows){const wrap=el('div',undefined,'table-scroll'),table=el('table'),head=el('thead'),tr=el('tr');headers.forEach(h=>{const th=el('th',h);th.scope='col';tr.append(th);});head.append(tr);const body=el('tbody');for(const cells of rows){const row=el('tr');cells.forEach(value=>{const td=el('td');if(value instanceof Node)td.append(value);else td.textContent=String(value);row.append(td);});body.append(row);}table.append(head,body);wrap.append(table);parent.append(wrap);}
 function jSource(value){const box=el('div',undefined,'journey-source'),source=value.source||value;const uri=source.uri||source.path;if(uri){box.append(el('span',(source.provenance||'runtime')+': '+uri+(finite(source.line)?':'+source.line:'')+(finite(source.column)?':'+source.column:'')));}for(const candidate of value.sourceCandidates||[]){box.append(el('span','Local candidate · '+candidate.path+':'+candidate.line+' · revision '+(candidate.revisionStatus||'unverified')));}if(!box.childNodes.length)box.append(el('span','Source location unavailable'));else{const value=box.textContent,button=el('button','Copy source references');button.type='button';button.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(value);button.textContent='Copied';}catch(_){const field=el('textarea');field.value=value;field.setAttribute('aria-label','Source references to copy');box.append(field);field.focus();field.select();}});box.append(button);}return box;}
 function jEmpty(parent,message){parent.append(el('p',message,'journey-evidence-note'));}
 function jDraw(){const svg=$('journey-chart');svg.replaceChildren();const w=650,h=225,x0=93,x=v=>x0+(v-jMin)/(jMax-jMin)*w;svg.setAttribute('viewBox','0 0 760 255');for(const[label,y]of [['Context',34],['Frames',83],['Dart heap',135],['CPU samples',184]]){svg.append(svgEl('text',{x:0,y,fill:'var(--muted)','font-size':11},label),svgEl('line',{x1:x0,y1:y+6,x2:x0+w,y2:y+6,stroke:'var(--line)'}));}
 const shade=svgEl('rect',{x:x(jInterval.startMicros),y:10,width:Math.max(1,x(jInterval.endMicros)-x(jInterval.startMicros)),height:205,fill:'var(--soft)',opacity:.6});svg.prepend(shade);
 for(const item of jItems.filter(i=>finite(i.startMicros))){const end=finite(item.endMicros)?item.endMicros:(item.observedEndMicros??jMax),y=item.type==='screen'?26:item.type==='operation'?40:13;const mark=svgEl('rect',{x:x(item.startMicros),y,width:Math.max(2,x(end)-x(item.startMicros)),height:8,fill:item.type==='operation'?'var(--raster)':'var(--build)',opacity:item.id===jActive?.id?1:.45});mark.append(svgEl('title',{},item.label+' · '+item.coverage));svg.append(mark);}
 let peak=finite(budget)?budget:1;for(const f of jFrames)peak=Math.max(peak,jPhase(f)/1000);const stride=Math.max(1,Math.ceil(jFrames.length/500));for(let i=0;i<jFrames.length;i+=stride){let f=jFrames[i];for(let k=i+1;k<Math.min(i+stride,jFrames.length);k++)if(jPhase(jFrames[k])>jPhase(f))f=jFrames[k];const mark=svgEl('line',{x1:x(f.startMicros),y1:99,x2:x(f.startMicros),y2:99-jPhase(f)/1000/peak*38,stroke:over(f)?'var(--warn)':'var(--build)','stroke-width':1.8});mark.append(svgEl('title',{},'Frame '+f.number+': build '+fmt(f.buildMicros/1000)+' ms, raster '+fmt(f.rasterMicros/1000)+' ms'));svg.append(mark);}
 let heapPeak=1;for(const m of jMemory)if(finite(m.heapUsage))heapPeak=Math.max(heapPeak,m.heapUsage);const heapPath=jMemory.filter(m=>finite(m.heapUsage)).map((m,i)=>(i?'L':'M')+x(m.micros)+','+(151-m.heapUsage/heapPeak*37)).join(' ');if(heapPath)svg.append(svgEl('path',{d:heapPath,fill:'none',stroke:'var(--raster)','stroke-width':2}));
 for(const mark of jGc){if(finite(mark.micros)){const line=svgEl('line',{x1:x(mark.micros),x2:x(mark.micros),y1:114,y2:151,stroke:'var(--warn)','stroke-dasharray':'2 3',opacity:.35});line.append(svgEl('title',{},'GC notification received here; collection time uncertain'));svg.append(line);}}
 for(const batch of jCpu){const samples=batch.samples||[],stride=Math.max(1,Math.ceil(samples.length/300));for(let i=0;i<samples.length;i+=stride)if(finite(samples[i].micros))svg.append(svgEl('line',{x1:x(samples[i].micros),x2:x(samples[i].micros),y1:174,y2:190,stroke:'var(--build)',opacity:.45}));}
 for(let i=0;i<=4;i++){const t=jMin+(jMax-jMin)*i/4;svg.append(svgEl('text',{x:x(t),y:h+8,'text-anchor':i===4?'end':i===0?'start':'middle',fill:'var(--muted)','font-size':10},fmt(t/1e6)+' s'));}svg.append(svgEl('text',{x:x0,y:251,fill:'var(--muted)','font-size':10},'Shared recording clock · gaps and idle periods are not dropped frames'));
 }
 function jRender(){
  const f=jFrames.filter(jInside),boundary=jFrames.filter(e=>jOverlap(e)&&!jInside(e)).length,m=jMemory.filter(jInside),g=jGc.filter(jOverlap),tr=jTraces.filter(jOverlap),wr=jRebuilds.filter(jInside);
  const builds=f.map(v=>v.buildMicros/1000).sort((a,b)=>a-b),rasters=f.map(v=>v.rasterMicros/1000).sort((a,b)=>a-b),slow=f.filter(over).length;
  const fnMap=new Map(),sampleSeen=new Set();let sampleCount=0;for(const batch of jCpu){if(jInterval.connection!=null&&batch.connection!=null&&String(jInterval.connection)!==String(batch.connection))continue;for(const sample of batch.samples||[]){if(!jInside({...sample,connection:batch.connection}))continue;const functions=batch.functions||[],signature=sample.identity||JSON.stringify([batch.segment,batch.isolate,sample.vmMicros,(sample.stack||[]).map(i=>{const f=functions[i];return f?[f.name,f.uri,f.line,f.column]:null;})]);if(sampleSeen.has(signature))continue;sampleSeen.add(signature);sampleCount++;for(const index of new Set(sample.stack||[])){const fn=functions[index];if(!fn)continue;const key=fn.key||JSON.stringify([fn.name,fn.uri,fn.line,fn.column]);if(!fnMap.has(key))fnMap.set(key,{...fn,samples:0,selfSamples:0});fnMap.get(key).samples++;if(index===sample.stack[0])fnMap.get(key).selfSamples++;}}}
  const functions=[...fnMap.values()].sort((a,b)=>b.selfSamples-a.selfSamples||b.samples-a.samples),heapValues=m.map(v=>v.heapUsage).filter(finite),rssValues=m.map(v=>v.rssBytes).filter(finite);let heapPeak=null,rssPeak=null;for(const n of heapValues)heapPeak=heapPeak===null?n:Math.max(heapPeak,n);for(const n of rssValues)rssPeak=rssPeak===null?n:Math.max(rssPeak,n);
  text('journey-duration',fmt((jInterval.endMicros-jInterval.startMicros)/1e6)+' s selected');text('journey-start-label',fmt(jInterval.startMicros/1e6)+' s');text('journey-end-label',fmt(jInterval.endMicros/1e6)+' s');
  text('journey-window',f.length+(!finite(jInterval.uncertaintyMicros)?' frames in approximate window':' attributable frames')+' · '+boundary+' boundary-overlapping frames · '+m.length+' memory snapshots · '+sampleCount+' CPU stack samples'+(!finite(jInterval.uncertaintyMicros)?' · timing uncertainty unknown: no exact attribution.':'.'));
  const path=[];let cursor=jActive,seen=new Set();while(cursor&&!seen.has(cursor.id)){seen.add(cursor.id);path.unshift(cursor.label);cursor=jById.get(cursor.parentId);}const where=path.length?path.join(' → '):'Selected journey';
  let finding=where+': ';if(!f.length)finding+='No fully linked frames are available in this window. Other signals may still help; missing frame data is not evidence of smooth rendering.';else if(!finite(budget))finding+=f.length+' frames were captured, but the refresh budget is unknown.';else finding+=slow?slow+' of '+f.length+' linked frames exceeded the phase budget. The worst build took '+fmt(builds.at(-1))+' ms and the worst raster took '+fmt(rasters.at(-1))+' ms.':'No linked frames exceeded the phase budget in this window.';
  if(jActive?.endMicros==null&&jActive)finding+=' This operation or screen was still open when observation ended; its complete duration is unknown.';
  if(!finite(jInterval.uncertaintyMicros))finding+=' These are nearby observations in an approximate window, not exact action attribution.';
  const appFunction=functions.find(jIsApp);if(appFunction)finding+=' Sampled stacks included '+(appFunction.name==='<anonymous closure>'?'application code at '+appFunction.uri+':'+(appFunction.line||'?'):appFunction.name)+'. Open Sampled code to inspect its source evidence; this is not proof of the cause.';
  text('journey-finding',finding);
  $('journey-stats').replaceChildren();for(const[value,label]of [[finite(percentile(builds,.95))?fmt(percentile(builds,.95))+' ms':'Unavailable','UI / build p95'],[finite(percentile(rasters,.95))?fmt(percentile(rasters,.95))+' ms':'Unavailable','Raster p95'],[finite(budget)&&f.length?slow+' / '+f.length:'Unavailable','Frames over phase budget'],[jBytes(heapPeak),'Peak Dart heap in snapshots'],[jBytes(rssPeak),'Peak process RSS'],[jCpu.length?String(sampleCount):'Not collected','CPU stack samples']]){const card=el('div',undefined,'journey-stat');card.append(el('strong',value),el('span',label));$('journey-stats').append(card);}
  for(const id of ['frames','memory','cpu','widgets'])$('journey-'+id+'-content').replaceChildren();
  if(f.length)jTable($('journey-frames-content'),['Frame','Recording time','UI / build','Raster','Budget'],f.slice().sort((a,b)=>jPhase(b)-jPhase(a)).slice(0,30).map(v=>[v.number,fmt(v.startMicros/1e6)+' s',fmt(v.buildMicros/1000)+' ms',fmt(v.rasterMicros/1000)+' ms',finite(budget)?over(v)?'Exceeded':'Within':'Unknown']));else jEmpty($('journey-frames-content'),jData.unalignedFrameCount?'No calibrated frames fall fully inside this selection. '+jData.unalignedFrameCount+' frames elsewhere in the report have no exact timeline match. Their raw measurements remain below.':'No fully contained frame samples in this selection.');
  if(f.length>30)jEmpty($('journey-frames-content'),'Showing the 30 slowest of '+f.length+' selected frames; all samples remain in report.json.');
  if(m.length){jTable($('journey-memory-content'),['Time','Dart heap','External memory','Process RSS','Heap groups'],m.slice(0,40).map(v=>[fmt(v.micros/1e6)+' s',jBytes(v.heapUsage),jBytes(v.externalUsage),jBytes(v.rssBytes),v.groupCount]));jEmpty($('journey-memory-content'),g.length+' GC notifications received near this selection (receipt-aligned; not exact collection times).'+(m.length>=2&&finite(m[0].heapUsage)&&finite(m.at(-1).heapUsage)?' Heap change between first and last retained snapshot: '+jBytes(m.at(-1).heapUsage-m[0].heapUsage)+'.':''));}else jEmpty($('journey-memory-content'),'No memory snapshots are available inside this selection. Inspect capture capabilities below.');
  const visibleFunctions=$('journey-app-code').checked?functions.filter(jIsApp):functions;
  if(visibleFunctions.length)jTable($('journey-cpu-content'),['Function on stack','Self samples','Inclusive share','Source evidence'],visibleFunctions.slice(0,25).map(fn=>[fn.name,fn.selfSamples,fmt(fn.samples*100/sampleCount,1)+'%',jSource(fn)]));else jEmpty($('journey-cpu-content'),$('journey-app-code').checked&&functions.length?'No application functions matched this selection. Clear the filter to inspect other runtime functions.':'No CPU stacks were captured in this interval. A diagnose run may expose samples when the runtime supports CPU profiling.');
  for(const state of (cap.telemetry?.connections||[]))if(state.tracingLimitation)jEmpty($('journey-widgets-content'),state.tracingLimitation);
  const widgetRows=[];for(const batch of wr)for(const widget of batch.widgets||[])widgetRows.push([widget.name,'Rebuilt '+widget.count+'×','Frame '+batch.frameNumber,jSource(widget)]);for(const trace of tr.filter(v=>v.category==='widget').sort((a,b)=>(b.endMicros-b.startMicros)-(a.endMicros-a.startMicros)))widgetRows.push([trace.name,'Trace '+fmt((trace.endMicros-trace.startMicros)/1000)+' ms',jInside(trace)?'Inside interval':'Overlaps boundary',jSource(trace)]);
  if(jActive?.source){$('journey-widgets-content').append(el('p','Declared context location (not measured widget cost):','journey-evidence-note'),jSource(jActive));}
  if(widgetRows.length)jTable($('journey-widgets-content'),['Widget / trace','Observed work','Association','Source evidence'],widgetRows.slice(0,40));else jEmpty($('journey-widgets-content'),'No widget rebuild or widget-duration evidence is available for this interval. Source candidates alone do not establish which widget caused a slow frame.');
  if(tr.some(v=>v.category!=='widget')){jEmpty($('journey-widgets-content'),'Other overlapping runtime traces:');jTable($('journey-widgets-content'),['Phase','Trace duration','Boundary'],tr.filter(v=>v.category!=='widget').slice(0,20).map(v=>[v.name,fmt((v.endMicros-v.startMicros)/1000)+' ms',jInside(v)?'Inside':'Overlaps']));}
  jDraw();
 }
 function jSelect(item){jActive=item;jInterval=item&&finite(item.startMicros)&&finite(item.endMicros??item.observedEndMicros)?{startMicros:item.startMicros,endMicros:item.endMicros??item.observedEndMicros,uncertaintyMicros:item.uncertaintyMicros,connection:item.connection}:{startMicros:jMin,endMicros:jMax,uncertaintyMicros:item?null:0};text('journey-selection-title',item?item.label:'Entire captured journey');text('journey-selection-note',item?(item.type+' · '+item.status+' · '+(item.comparisonLimitation?item.comparisonLimitation+' ':'')+(item.limitation||'Explicit boundaries; evidence near an uncertain boundary is not attributed.')):'Every signal below uses the same selected interval. Sources identify evidence, not a proven cause.');$('journey-start').value=String(jInterval.startMicros);$('journey-end').value=String(jInterval.endMicros);for(const button of $('journey-items').querySelectorAll('button'))button.setAttribute('aria-current',String(button.dataset.item===item?.id));jRender();}
 for(const item of jItems){let depth=0,parent=item.parentId,visited=new Set([item.id]);while(parent&&jById.has(parent)&&!visited.has(parent)){visited.add(parent);depth++;parent=jById.get(parent).parentId;}const button=el('button',undefined,'journey-item depth-'+Math.min(depth,3));button.type='button';button.dataset.item=item.id;button.append(el('span',item.type,'journey-kind'),el('span',item.label),el('small',item.status+(item.metrics?.frameCount===0?' · no linked frames':finite(item.metrics?.overBudgetCount)?' · '+item.metrics.overBudgetCount+' slow frames':'')+' · '+(finite(item.durationMs)?fmt(item.durationMs/1000)+' s':'duration unavailable')+(item.coverage!=='bounded'?' · '+item.coverage:'')));button.addEventListener('click',()=>jSelect(item));$('journey-items').append(button);}
 if(!jItems.length)$('journey-items').append(el('p','No named intervals were captured. The recorder still shows available telemetry. Add app context or use a supported runner event adapter to name screens and operations.','subtle'));
 for(const limit of jData.limitations||[])$('journey-limits').append(el('li',limit));text('journey-capabilities',JSON.stringify(cap.telemetry||jData.capabilities||{},null,2));
 for(const id of ['journey-start','journey-end']){$(id).min=String(jMin);$(id).max=String(jMax);$(id).step=String(Math.max(1,Math.round((jMax-jMin)/1000)));$(id).addEventListener('input',()=>{let start=+$('journey-start').value,end=+$('journey-end').value;if(start>end){if(id==='journey-start')end=start;else start=end;}jInterval={startMicros:start,endMicros:end,uncertaintyMicros:0};jActive=null;text('journey-selection-title','Custom time interval');text('journey-selection-note','All panels follow this explicit recording-clock selection.');$('journey-start').value=String(start);$('journey-end').value=String(end);for(const b of $('journey-items').querySelectorAll('button'))b.setAttribute('aria-current','false');jRender();});}
 const tabNames=['frames','memory','cpu','widgets'];function jTab(name,focus=false){for(const n of tabNames){const active=n===name,button=$('journey-tab-'+n);button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;$('journey-evidence-'+n).hidden=!active;}if(focus)$('journey-tab-'+name).focus();}for(const[name,index]of tabNames.map((n,i)=>[n,i])){const button=$('journey-tab-'+name);button.addEventListener('click',()=>jTab(name));button.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();jTab(tabNames[e.key==='Home'?0:e.key==='End'?3:(index+(e.key==='ArrowRight'?1:3))%4],true);}});}
 $('journey-all').addEventListener('click',()=>jSelect(null));$('journey-app-code').addEventListener('change',jRender);
 window.runalongSelectJourney=id=>{const item=jById.get(id);if(!item)return;jSelect(item);$('journey-selection-title').focus();$('journey-panel').scrollIntoView({block:'start',behavior:'auto'});};
 window.addEventListener('resize',jDraw);const firstFinding=jItems.filter(i=>i.type==='operation'&&i.coverage==='bounded'&&(i.metrics?.overBudgetCount||0)>0).sort((a,b)=>b.metrics.overBudgetCount-a.metrics.overBudgetCount)[0];jSelect(firstFinding||null);
}
''';
